version: '3.4'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - MSSQL_SA_PASSWORD=FarmaciaApi.2024
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - backend
    healthcheck:
        test: ["CMD-SHELL", "echo 'SELECT 1' | /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P FarmaciaApi.2024"]
        interval: 10s
        timeout: 5s
        retries: 5

  api:
    #image: farmaciaapi
    build:
      context: .
      dockerfile: FarmaciaApi/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"  # Exponiendo el puerto 8080
    networks:
      - backend

volumes:
  sqlvolume:

networks:
  backend:
    driver: bridge
